dist: trusty
sudo: required
language: bash
cache:
  directories:
  - /usr/local
  - $ROOT_PROJECT/terraform/stage
  - $ROOT_PROJECT/terraform/prod
before_install:
  - curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-09/run.sh | bash
  - export ROOT_PROJECT=`pwd`
  - cd /usr/local/src
  - sudo wget https://releases.hashicorp.com/packer/1.3.1/packer_1.3.1_linux_386.zip
  - sudo unzip packer_*.zip
  - sudo rm -f packer_*.zip
  - sudo mv /usr/local/src/packer /usr/local/bin/
  - packer -v

  - sudo wget https://releases.hashicorp.com/terraform/0.11.9/terraform_0.11.9_linux_386.zip
  - sudo unzip terraform_*.zip
  - sudo rm -f terraform_*.zip
  - sudo mv /usr/local/src/terraform /usr/local/bin/
  - terraform -v

  - sudo wget https://github.com/wata727/tflint/releases/download/v0.7.2/tflint_linux_386.zip
  - sudo unzip tflint_*.zip
  - sudo rm -f tflint_*.zip
  - sudo mv /usr/local/src/tflint /usr/local/bin/
  - tflint -v

  - sudo pip2 install ansible-lint
  - ansible-lint --version
  - cd $ROOT_PROJECT
script:
  - packer validate -var-file=packer/variables.json.example packer/app.json
  - packer validate -var-file=packer/variables.json.example packer/db.json
  - packer validate -var-file=packer/variables.json.example packer/immutable.json
  - packer validate -var-file=packer/variables.json.example packer/ubuntu16.json

  - cd $ROOT_PROJECT/terraform/stage
  - rm backend.tf
  - mv terraform.tfvars.example terraform.tfvars
  - terraform init
  - terraform validate -check-variables=false
  - tflint

  - cd $ROOT_PROJECT/terraform/prod
  - rm backend.tf
  - mv terraform.tfvars.example terraform.tfvars
  - terraform init
  - terraform validate -check-variables=false
  - tflint

  - cd $ROOT_PROJECT/ansible
  - ansible-lint playbooks/*.yml
notifications:
  slack:
    rooms:
      secure: JPLTHfuAXDdqRc1j8omKrQisb/5ZP8Ac40b6AXMJyujqvjS8sdUH0z5urwC61XbEVdEBxpowQCb5u5fa1YfSALdVLWnZWFFVIputx5oMCXTBkY/OU/hqJifB/yHZ0awCg1nigzbCY8VMpxmNnEvPkXhslF5pLV4h6VwDhMNzX5AXJWcs5BzlNghszmhErsjNX82YcqcOLV1IOdRZh8IIMqIJla3YyrXGRTL/pmUkaHv8yT1WSTLCA36U/49tPQH8v3AP73fab7iULtvmdNqQDB65EPRXWOHQwGdpstyckGz3K7CPfTXw0paKSr1uUoDuugBsF/TBlyOA7hHoPY8tt0IjwWOV1eCHI7iUeJDO4L/aS1Y/uHHoZq37SVLSmParK9mErumksAHuX1rP3JKj2oS7bJzRPCBVCQiIVyvK9xRqFH2YXnTkyRqcmSnkSqQd9zl64pmkwvW9mTiIv03nb4uBOoFJ9/zz69dj5Jdn7b+ksnLhSdoSMibrY+GNhsSgK6P/nHjyTsEJuKv9Ir8dWgxKZpP+fqn4jRJfDmg5rGqRuvrf4D92FTopx8IjXE454XBZriBbyYxidX1GHcYEeccOcGlhZEfEi12yIaUxJNFIHkivBsE53qiSr45G4e54QmTSXEJMg3mFl+XFl3+04crDKHurVOWPUdmWi1GBBXM=
