---
- name: Add an apt key by id from a keyserver
  tags: install
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: EA312927
- name: Add MongoDB repository
  tags: install
  apt_repository:
    repo: deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
    filename: mongodb-org-3.2.list
- name: Install MongoDB server
  tags: install
  apt:
    name: mongodb-org
- name: Enable MongoDB
  tags: install
  systemd:
    name: mongod
    enabled: yes
